on: [push, workflow_dispatch]

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        npm-version: ["7.0.7", "7.0.8"]

    env:
      VERSION: ${{ matrix.npm-version }}-${{ github.run_number }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          scope: ${{ github.repository_owner }}
          registry-url: https://npm.pkg.github.com

      - name: Create a package called @${{ github.repository }}
        run: npm init --scope ${{ github.repository_owner }} -y

      - name: Add index.js to package
        run: echo 'exports.sayHello = () => { console.log("Hello from ${{ github.repository }}!") }' > index.js

      - name: Set package version to ${{ env.VERSION }}
        run: npm version ${{ env.VERSION }} --no-git-tag-version

      - name: Build the package
        run: npm pack

      - name: Publish the package
        run: npx npm@${{ matrix.npm-version }} publish
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
